// 单元测试
// 测试接口文件
### 登陆
POST http://192.168.1.105:18082/user/login HTTP/1.1
content-type: application/json

{
  "userName": "504",
  "password": "1213"
}
###
GET  http://192.168.1.105:18082/iopGroup/iopGroups HTTP/1.1
content-type: application/json
